"""Version identifiers for deterministic repository navigation artifacts."""

SEMANTIC_GRAPH_VERSION = "semantic-ts-v2"
PROJECT_MAP_VERSION = "project-map-v2"
FEATURE_CATALOG_VERSION = "feature-catalog-v2"
FEATURE_FLOW_VERSION = "feature-flow-v3"
CODE_EXPLANATION_VERSION = "minimum-sufficient-v1"
CHANGE_BRIEF_VERSION = "change-brief-v1"
ARCHITECTURE_GRAPH_VERSION = "architecture-graph-v2"
ARCHITECTURE_LABEL_VERSION = "architecture-labels-v1"
REPOSITORY_STORY_VERSION = "repository-story-v1"
